insert into t_color_cilindro (A_NRO_CILINDRO, F_COLOR_P_ID, F_VARIANTE_P_ID) select -1, F_COLOR_P_ID, F_VARIANTE_P_ID FROM t_color_variante;
insert into t_color_cilindro (F_COLOR_P_ID, F_VARIANTE_P_ID) select F_COLOR_FONDO_P_ID, P_ID FROM T_VARIANTE;

ALTER TABLE t_variante DROP FOREIGN KEY FK11A9400B6A259ECF;
ALTER TABLE t_variante DROP INDEX FK11A9400B6A259ECF;
ALTER TABLE t_variante DROP COLUMN F_COLOR_FONDO_P_ID;

DROP TABLE T_COLOR_VARIANTE;




