UPDATE T_MODULO SET A_SISTEMA=0; --CORRER EN A Y EN B
ALTER TABLE T_MODULO MODIFY COLUMN A_SISTEMA BIT(1) DEFAULT 0;

INSERT INTO T_MODULO (P_ID, A_NOMBRE, A_TRIGGER, A_SERVICIO, A_SISTEMA) VALUES (116,'Sistema GTL - Terminal',0,0,1);

