ALTER TABLE t_movimiento ADD UNIQUE INDEX UNIQUE_REC_CLI(F_RECIBO_P_ID);
ALTER TABLE t_movimiento ADD UNIQUE INDEX UNIQUE_FC_CLI(F_FACTURA_P_ID);
ALTER TABLE t_movimiento ADD UNIQUE INDEX UNIQUE_NC_CLI(F_NOTA_CREDITO_P_ID);
ALTER TABLE t_movimiento ADD UNIQUE INDEX UNIQUE_ND_CLI(F_NOTA_DEBITO_P_ID);

ALTER TABLE t_movimiento ADD UNIQUE INDEX UNIQUE_ODP(F_ORDEN_PAGO_P_ID);
ALTER TABLE t_movimiento ADD UNIQUE INDEX UNIQUE_FC_PROV(F_FACTURA_PROV_P_ID);
ALTER TABLE t_movimiento ADD UNIQUE INDEX UNIQUE_NC_PROV(F_NOT_CRED_P_ID);
ALTER TABLE t_movimiento ADD UNIQUE INDEX UNIQUE_ND_PROV(F_NOT_DEB_PROV_P_ID);
