-- AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

-- REEMPLAZO EL ARTÍCULO EN EL NOMBRE DEL PRODUCTO
UPDATE T_PRODUCTO PR
INNER JOIN T_ARTICULO ART ON ART.P_ID = PR.F_ARTICULO_P_ID
SET PR.A_DESCR = REPLACE(PR.A_DESCR, CONCAT ('- ',ART.A_NOMBRE), '');

UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, '- AP 2.50', '');
UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, '- AP 1,50', '');
UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, 'AP240', '');
UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, '- AA 1.50', '');
UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, '- AA 2.50', '');
UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, '- AP 2.10', '');
UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, '- AP 2.80', '');
UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, '- PONGEE 1.42', '');
UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, '- AP 1.75', '');
UPDATE T_PRODUCTO PR SET A_DESCR = REPLACE(PR.A_DESCR, '- AP 2.73', '');


-- CREO UNA TABLA HELPER TEMPORAL PRODUCTO y LA LLENO LA TABLA T_PRODUCTO_ARTICULO POR CADA TIPO DE PRODUCTO
grant all on gtl.T_PRODUCTO_ARTICULO to 'root'@'192.168.1.13' identified by 's4l3m';

CREATE TABLE `T_PRODUCTO_TMP` (
  `TIPO` VARCHAR(31) NOT NULL,
  `P_ID` INT(11) NOT NULL,
  `A_DESCR` VARCHAR(255),
  `F_GAMA_P_ID` INT(11) DEFAULT NULL,
  `F_DIBUJO_P_ID` INT(11) DEFAULT NULL,
  `F_VARIANTE_P_ID` INT(11) DEFAULT NULL,
  `F_COLOR_P_ID` INT(11) DEFAULT NULL
);

grant all on gtl.T_PRODUCTO_TMP to 'root'@'192.168.1.13' identified by 's4l3m';

INSERT INTO T_PRODUCTO_TMP (P_ID, A_DESCR, TIPO, F_GAMA_P_ID, F_COLOR_P_ID)
SELECT P_ID, A_DESCR, TIPO, F_GAMA_P_ID, F_COLOR_P_ID
FROM T_PRODUCTO
WHERE TIPO = 'TENIDO'
GROUP BY TIPO, F_GAMA_P_ID, F_COLOR_P_ID;

INSERT INTO  T_PRODUCTO_ARTICULO (F_PRODUCTO_P_ID, F_ARTICULO_P_ID)
SELECT TMP.P_ID,Z.F_ARTICULO_P_ID
FROM (
  SELECT TIPO, F_GAMA_P_ID, F_COLOR_P_ID, F_ARTICULO_P_ID
  FROM T_PRODUCTO P
  WHERE P.TIPO = 'TENIDO'
  GROUP BY TIPO, F_GAMA_P_ID, F_COLOR_P_ID, F_ARTICULO_P_ID
) Z INNER JOIN T_PRODUCTO_TMP TMP ON TMP.TIPO=Z.TIPO AND TMP.F_GAMA_P_ID = Z.F_GAMA_P_ID AND TMP.F_COLOR_P_ID =Z.F_COLOR_P_ID;

INSERT INTO T_PRODUCTO_TMP (P_ID, A_DESCR, TIPO, F_DIBUJO_P_ID, F_VARIANTE_P_ID)
SELECT P_ID, A_DESCR, TIPO, F_DIBUJO_P_ID, F_VARIANTE_P_ID
FROM T_PRODUCTO
WHERE TIPO = 'ESTAMPADO'
GROUP BY TIPO, F_DIBUJO_P_ID, F_VARIANTE_P_ID;

INSERT INTO  T_PRODUCTO_ARTICULO (F_PRODUCTO_P_ID, F_ARTICULO_P_ID)
SELECT TMP.P_ID,Z.F_ARTICULO_P_ID
FROM (
  SELECT TIPO, F_DIBUJO_P_ID, F_VARIANTE_P_ID, F_ARTICULO_P_ID
  FROM T_PRODUCTO P
  WHERE P.TIPO = 'ESTAMPADO'
  GROUP BY TIPO, F_DIBUJO_P_ID, F_VARIANTE_P_ID, F_ARTICULO_P_ID
) Z INNER JOIN T_PRODUCTO_TMP TMP ON TMP.TIPO=Z.TIPO AND TMP.F_DIBUJO_P_ID = Z.F_DIBUJO_P_ID AND TMP.F_VARIANTE_P_ID =Z.F_VARIANTE_P_ID;

INSERT INTO T_PRODUCTO_TMP (P_ID, A_DESCR, TIPO)
SELECT P_ID, A_DESCR, TIPO
FROM T_PRODUCTO
WHERE TIPO NOT IN ('ESTAMPADO','TENIDO')
GROUP BY TIPO;

INSERT INTO  T_PRODUCTO_ARTICULO (F_PRODUCTO_P_ID, F_ARTICULO_P_ID)
SELECT TMP.P_ID,Z.F_ARTICULO_P_ID
FROM (
  SELECT TIPO, NULL AS F_ARTICULO_P_ID
  FROM T_PRODUCTO P
  WHERE P.TIPO NOT IN ('ESTAMPADO', 'TENIDO')
  GROUP BY TIPO
) Z INNER JOIN T_PRODUCTO_TMP TMP ON TMP.TIPO=Z.TIPO;

-- CHECK:
SELECT COUNT(*)
FROM (
    SELECT F_PRODUCTO_P_ID
    FROM T_PRODUCTO_ARTICULO
    GROUP BY F_PRODUCTO_P_ID
) X;

SELECT COUNT(*) FROM T_PRODUCTO_TMP;

-- INSERTO REGISTROS EN LA TABLA ASOC DE REMITO DE ENTRADA
INSERT INTO T_REMITO_ENTRADA_PRODUCTO_ART_ASOC
SELECT ASOC.F_REMITO_ENTRADA_P_ID, PA.P_ID
FROM T_REMITO_ENTRADA_PRODUCTO ASOC
INNER JOIN T_PRODUCTO PR ON PR.P_ID = ASOC.F_PRODUCTO_P_ID
INNER JOIN T_PRODUCTO_TMP TMP ON TMP.TIPO=PR.TIPO AND ((TMP.F_GAMA_P_ID IS NULL AND PR.F_GAMA_P_ID IS NULL) OR TMP.F_GAMA_P_ID = PR.F_GAMA_P_ID) AND ((TMP.F_DIBUJO_P_ID IS NULL AND PR.F_DIBUJO_P_ID IS NULL) OR TMP.F_DIBUJO_P_ID = PR.F_DIBUJO_P_ID) AND ((TMP.F_COLOR_P_ID IS NULL AND PR.F_COLOR_P_ID IS NULL) OR TMP.F_COLOR_P_ID = PR.F_COLOR_P_ID) AND ((TMP.F_VARIANTE_P_ID IS NULL AND  PR.F_VARIANTE_P_ID IS NULL) OR TMP.F_VARIANTE_P_ID = PR.F_VARIANTE_P_ID)
INNER JOIN T_PRODUCTO_ARTICULO PA ON PA.F_PRODUCTO_P_ID = TMP.P_ID
WHERE (PR.F_ARTICULO_P_ID IS NULL AND PA.F_ARTICULO_P_ID IS NULL) OR PA.F_ARTICULO_P_ID = PR.F_ARTICULO_P_ID;

-- ACTUALIZO COLUMNA F_PRODUCTO_ARTICULO DE ODT
UPDATE T_ORDEN_DE_TRABAJO ODT
INNER JOIN T_PRODUCTO PR ON PR.P_ID = ODT.F_PRODUCTO_P_ID
INNER JOIN T_PRODUCTO_TMP TMP ON TMP.TIPO=PR.TIPO AND ((TMP.F_GAMA_P_ID IS NULL AND PR.F_GAMA_P_ID IS NULL) OR TMP.F_GAMA_P_ID = PR.F_GAMA_P_ID) AND ((TMP.F_DIBUJO_P_ID IS NULL AND PR.F_DIBUJO_P_ID IS NULL) OR TMP.F_DIBUJO_P_ID = PR.F_DIBUJO_P_ID) AND ((TMP.F_COLOR_P_ID IS NULL AND PR.F_COLOR_P_ID IS NULL) OR TMP.F_COLOR_P_ID = PR.F_COLOR_P_ID) AND ((TMP.F_VARIANTE_P_ID IS NULL AND  PR.F_VARIANTE_P_ID IS NULL) OR TMP.F_VARIANTE_P_ID = PR.F_VARIANTE_P_ID)
INNER JOIN T_PRODUCTO_ARTICULO PA ON PA.F_PRODUCTO_P_ID = TMP.P_ID
SET ODT.F_PRODUCTO_ARTICULO_P_ID = PA.P_ID
WHERE (PR.F_ARTICULO_P_ID IS NULL AND PA.F_ARTICULO_P_ID IS NULL) OR PA.F_ARTICULO_P_ID = PR.F_ARTICULO_P_ID;

-- ACTUALIZO COLUMNA F_PRODUCTO_ARTICULO DE T_ITEM_FACTURA
UPDATE T_ITEM_FACTURA IFF
INNER JOIN T_PRODUCTO PR ON PR.P_ID = IFF.F_PRODUCTO_P_ID
INNER JOIN T_PRODUCTO_TMP TMP ON TMP.TIPO=PR.TIPO AND ((TMP.F_GAMA_P_ID IS NULL AND PR.F_GAMA_P_ID IS NULL) OR TMP.F_GAMA_P_ID = PR.F_GAMA_P_ID) AND ((TMP.F_DIBUJO_P_ID IS NULL AND PR.F_DIBUJO_P_ID IS NULL) OR TMP.F_DIBUJO_P_ID = PR.F_DIBUJO_P_ID) AND ((TMP.F_COLOR_P_ID IS NULL AND PR.F_COLOR_P_ID IS NULL) OR TMP.F_COLOR_P_ID = PR.F_COLOR_P_ID) AND ((TMP.F_VARIANTE_P_ID IS NULL AND  PR.F_VARIANTE_P_ID IS NULL) OR TMP.F_VARIANTE_P_ID = PR.F_VARIANTE_P_ID)
INNER JOIN T_PRODUCTO_ARTICULO PA ON PA.F_PRODUCTO_P_ID = TMP.P_ID
SET IFF.F_PRODUCTO_ARTICULO_P_ID = PA.P_ID
WHERE (PR.F_ARTICULO_P_ID IS NULL AND PA.F_ARTICULO_P_ID IS NULL) OR PA.F_ARTICULO_P_ID = PR.F_ARTICULO_P_ID;

-- ELIMINO FKS Y COLUMNAS QUE NO USO MÁS
ALTER TABLE T_ITEM_FACTURA DROP FOREIGN KEY FK92BFBC37492D6957;
ALTER TABLE T_ORDEN_DE_TRABAJO DROP FOREIGN KEY FK61B84C9492D6957;
ALTER TABLE T_REMITO_ENTRADA_PRODUCTO DROP FOREIGN KEY FK51A7152492D6957;
ALTER TABLE T_ITEM_FACTURA DROP COLUMN F_PRODUCTO_P_ID;
ALTER TABLE T_ORDEN_DE_TRABAJO DROP COLUMN F_PRODUCTO_P_ID;
ALTER TABLE T_REMITO_ENTRADA_PRODUCTO DROP COLUMN F_PRODUCTO_P_ID;
DROP TABLE T_REMITO_ENTRADA_PRODUCTO;

-- BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
CREATE TABLE `t_producto_articulo` (
  `P_ID` int(11) NOT NULL,
  `F_PRODUCTO_P_ID` int(11) NOT NULL,
  `F_ARTICULO_P_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`P_ID`)
) ENGINE=FEDERATED CONNECTION='mysql://root:s4l3m@192.168.1.250:3306/gtl/t_producto_articulo';

CREATE TABLE `T_PRODUCTO_TMP` (
  `TIPO` VARCHAR(31) NOT NULL,
  `P_ID` INT(11) NOT NULL,
  `A_DESCR` VARCHAR(255),
  `F_GAMA_P_ID` INT(11) DEFAULT NULL,
  `F_DIBUJO_P_ID` INT(11) DEFAULT NULL,
  `F_VARIANTE_P_ID` INT(11) DEFAULT NULL,
  `F_COLOR_P_ID` INT(11) DEFAULT NULL
) ENGINE=FEDERATED CONNECTION='mysql://root:s4l3m@192.168.1.250:3306/gtl/t_producto_tmp';

INSERT INTO T_REMITO_ENTRADA_PRODUCTO_ART_ASOC
SELECT ASOC.F_REMITO_ENTRADA_P_ID, PA.P_ID
FROM T_REMITO_ENTRADA_PRODUCTO ASOC
INNER JOIN T_PRODUCTO PR ON PR.P_ID = ASOC.F_PRODUCTO_P_ID
INNER JOIN T_PRODUCTO_TMP TMP ON TMP.TIPO=PR.TIPO AND ((TMP.F_GAMA_P_ID IS NULL AND PR.F_GAMA_P_ID IS NULL) OR TMP.F_GAMA_P_ID = PR.F_GAMA_P_ID) AND ((TMP.F_DIBUJO_P_ID IS NULL AND PR.F_DIBUJO_P_ID IS NULL) OR TMP.F_DIBUJO_P_ID = PR.F_DIBUJO_P_ID) AND ((TMP.F_COLOR_P_ID IS NULL AND PR.F_COLOR_P_ID IS NULL) OR TMP.F_COLOR_P_ID = PR.F_COLOR_P_ID) AND ((TMP.F_VARIANTE_P_ID IS NULL AND  PR.F_VARIANTE_P_ID IS NULL) OR TMP.F_VARIANTE_P_ID = PR.F_VARIANTE_P_ID)
INNER JOIN T_PRODUCTO_ARTICULO PA ON PA.F_PRODUCTO_P_ID = TMP.P_ID
WHERE (PR.F_ARTICULO_P_ID IS NULL AND PA.F_ARTICULO_P_ID IS NULL) OR PA.F_ARTICULO_P_ID = PR.F_ARTICULO_P_ID;

UPDATE T_ORDEN_DE_TRABAJO ODT
INNER JOIN T_PRODUCTO PR ON PR.P_ID = ODT.F_PRODUCTO_P_ID
INNER JOIN T_PRODUCTO_TMP TMP ON TMP.TIPO=PR.TIPO AND ((TMP.F_GAMA_P_ID IS NULL AND PR.F_GAMA_P_ID IS NULL) OR TMP.F_GAMA_P_ID = PR.F_GAMA_P_ID) AND ((TMP.F_DIBUJO_P_ID IS NULL AND PR.F_DIBUJO_P_ID IS NULL) OR TMP.F_DIBUJO_P_ID = PR.F_DIBUJO_P_ID) AND ((TMP.F_COLOR_P_ID IS NULL AND PR.F_COLOR_P_ID IS NULL) OR TMP.F_COLOR_P_ID = PR.F_COLOR_P_ID) AND ((TMP.F_VARIANTE_P_ID IS NULL AND  PR.F_VARIANTE_P_ID IS NULL) OR TMP.F_VARIANTE_P_ID = PR.F_VARIANTE_P_ID)
INNER JOIN T_PRODUCTO_ARTICULO PA ON PA.F_PRODUCTO_P_ID = TMP.P_ID
SET ODT.F_PRODUCTO_ARTICULO_P_ID = PA.P_ID
WHERE (PR.F_ARTICULO_P_ID IS NULL AND PA.F_ARTICULO_P_ID IS NULL) OR PA.F_ARTICULO_P_ID = PR.F_ARTICULO_P_ID;

UPDATE T_ITEM_FACTURA IFF
INNER JOIN T_PRODUCTO PR ON PR.P_ID = IFF.F_PRODUCTO_P_ID
INNER JOIN T_PRODUCTO_TMP TMP ON TMP.TIPO=PR.TIPO AND ((TMP.F_GAMA_P_ID IS NULL AND PR.F_GAMA_P_ID IS NULL) OR TMP.F_GAMA_P_ID = PR.F_GAMA_P_ID) AND ((TMP.F_DIBUJO_P_ID IS NULL AND PR.F_DIBUJO_P_ID IS NULL) OR TMP.F_DIBUJO_P_ID = PR.F_DIBUJO_P_ID) AND ((TMP.F_COLOR_P_ID IS NULL AND PR.F_COLOR_P_ID IS NULL) OR TMP.F_COLOR_P_ID = PR.F_COLOR_P_ID) AND ((TMP.F_VARIANTE_P_ID IS NULL AND  PR.F_VARIANTE_P_ID IS NULL) OR TMP.F_VARIANTE_P_ID = PR.F_VARIANTE_P_ID)
INNER JOIN T_PRODUCTO_ARTICULO PA ON PA.F_PRODUCTO_P_ID = TMP.P_ID
SET IFF.F_PRODUCTO_ARTICULO_P_ID = PA.P_ID
WHERE (PR.F_ARTICULO_P_ID IS NULL AND PA.F_ARTICULO_P_ID IS NULL) OR PA.F_ARTICULO_P_ID = PR.F_ARTICULO_P_ID;

ALTER TABLE T_ITEM_FACTURA DROP COLUMN F_PRODUCTO_P_ID;
ALTER TABLE T_ORDEN_DE_TRABAJO DROP COLUMN F_PRODUCTO_P_ID;
ALTER TABLE T_REMITO_ENTRADA_PRODUCTO DROP COLUMN F_PRODUCTO_P_ID;
DROP TABLE T_REMITO_ENTRADA_PRODUCTO;
DROP TABLE T_PRODUCTO_TMP;

-- AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

ALTER TABLE T_PRODUCTO DROP COLUMN F_ARTICULO_P_ID;
DELETE FROM T_PRODUCTO WHERE P_ID NOT IN (SELECT F_PRODUCTO_P_ID FROM T_PRODUCTO_ARTICULO);
DROP TABLE T_PRODUCTO_TMP;