INSERT INTO T_MODULO VALUES
 (1,'ar.com.textillevel.gui.modulos.cheques.ModuloCheques','Administrar Cheques'),
 (2,'ar.com.textillevel.gui.modulos.abm.gente.GuiABMCliente','Administrar Clientes'),
 (3,'ar.com.textillevel.gui.modulos.abm.gente.GuiABMProveedor','Administrar Proveedores'),
 (4,'ar.com.textillevel.gui.modulos.abm.gente.GuiABMPersona','Administrar Personas'),
 (5,'ar.com.textillevel.gui.modulos.agenda.ModuloAgenda','Agenda'),
 (6,'ar.com.textillevel.gui.modulos.abm.GuiABMProductos','Administrar Productos'),
 (7,'ar.com.textillevel.gui.modulos.abm.GuiABMListaDePrecios','Administrar Listas de Precios'),
 (8,'ar.com.textillevel.gui.modulos.abm.GuiABMArticulos','Administrar Artículos'),
 (10,'ar.com.textillevel.gui.modulos.abm.gente.GuiABMInfoLocalidad','Administrar Localidades'),
 (11,'ar.com.textillevel.gui.modulos.abm.gente.GuiABMRubro','Administrar Rubros'),
 (12,'ar.com.textillevel.gui.modulos.abm.GuiABMColor','Administrar Colores'),
 (13,'ar.com.textillevel.gui.modulos.abm.GuiABMGamas','Administrar Gamas de colores'),
 (14,'ar.com.textillevel.gui.modulos.abm.GuiABMDibujoEstampado','Administrar Dibujos de Estampados'),
 (15,'ar.com.textillevel.gui.modulos.abm.GuiABMBancos','Administrar Bancos'),
 (16,'ar.com.textillevel.gui.modulos.abm.GuiABMCondicionDeVenta','Administrar Condiciones de venta'),
 (17,'ar.com.textillevel.gui.modulos.abm.portal.GuiABMPerfil','Administrar Perfiles de usuario'),
 (18,'ar.com.textillevel.gui.modulos.abm.portal.GuiABMUsuarioSistema','Administrar usuarios'),
 (19,'main.acciones.facturacion.AgregarRemitoEntradaAction','Agregar Remito de Entrada'),
 (20,'main.acciones.facturacion.AgregarRemitoSalidaAction','Agregar Remito de Salida'),
 (21,'main.acciones.facturacion.AgregarFacturaAction','Agregar factura'),
 (22,'main.acciones.facturacion.AgregarCorreccionAction','Agregar nota de débito o crédito'),
 (23,'main.acciones.facturacion.AgregarReciboAction','Agregar Recibo'),
 (24,'main.acciones.facturacion.ConsultarFacturaAction','Consultar factura'),
 (25,'main.acciones.facturacion.ConsultarCorreccionesAction','Consultar notas de crédito y débito'),
 (26,'main.acciones.facturacion.ConsultarRemitoEntradaAction','Consultar remito de entrada'),
 (27,'main.acciones.facturacion.ConsultarRemitoSalidaAction','Consultar remito de salida'),
 (28,'main.acciones.facturacion.ConsultarReciboAction','Consultar recibo'),
 (29,'main.acciones.cuentas.VerMovimientosCuentaAction','Ver movimientos de cuentas'),
 (30,'main.acciones.parametrosgenerales.ModificarParametrosGeneralesAction','Modificar parametros generales');
 (34,'ar.com.textillevel.gui.modulos.abm.GuiABMListaDePreciosProveedor','Administrar Lista de Precios');

