ALTER TABLE `gtl`.`t_pers_recibo_sueldo` ADD UNIQUE INDEX `IX_LEGAJO_TEXTO_ORDEN`(`F_LEGAJO_P_ID`, `A_TEXTO_ORDEN`);

ALTER TABLE `gtl`.`t_pers_valor_puesto` DROP COLUMN `F_CATEGORIA_P_ID`, DROP FOREIGN KEY `FK14CE3EA7C3009089`;

ALTER TABLE `gtl`.`t_pers_vale_atencion` MODIFY COLUMN `A_MINUTOS` INT(11) DEFAULT NULL;
