-- TODO:
-- LLENAR ESTA TABLA COMPLETAMENTE A MANO, SON POCOS REGISTROS
-- HACERLO UNA VEZ QUE SE HAYAN RESUELTO TODOS LOS NULLS DE T_PRECIO_MATERIA_PRIMA_EQUIV.sql

CREATE TABLE `T_REL_CONT_PREC_MAT_PRIMA_EQUIV` (
  `P_ID` INT(10) NULL,
  `CONTENEDOR` VARCHAR(100) NULL,
  `P_ID_A` INT(10) NULL
);
