-- EJECUTAR LA B:
CREATE TABLE `T_PROVEEDORES_EQUIV` (
  `P_ID` INT(10) NULL,
  `A_RAZONSOCIAL` VARCHAR(255) NULL,
  `A_RAZONSOCIAL_A` VARCHAR(255) NULL,
  `P_ID_A` INT(10) NULL
);


-- EJECUTAR INSERTS EN LA B (VER COMO GENERARLOS ABAJO EN "PASOS PARA GENERAR LOS INSERTS"):

INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (1,"SANYOCOLOR S.A.","SANYOCOLOR S.A.",1);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (2,"PRODUCTOS QUIMICOS AURIAL S.R.L",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (3,"CASARES Y CIA. S.R.L",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (4,"DALGAR S.A",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (5,"ELECTROFASE S.A",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (6,"MICHELI S.A",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (7,"NESTLE WATERS ARGENTINA S.A","NESTLE WATERS ARGENTINA S.A",7);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (8,"TANATEX CHEMICALS ARGENTINA S.A","TANATEX CHEMICALS ARGENTINA S.A",8);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (9,"VORTEX ARGENTINA S.A","VORTEX ARGENTINA S.A",9);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (10,"INTERSISTEMAS SEGURIDAD ELECTRONICA","INTERSISTEMAS SEGURIDAD ELECTRONICA",10);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (11,"INSUMA S.R.L",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (12,"SODIMAC FALABELLA S.A",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (13,"EQUITECNICA S.A","EQUITECNICA S.A",13);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (14,"MORAN HNOS. S.R.L",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (15,"WIRE PC.COM ","WIRE PC.COM ",15);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (16,"RADIADORES SAN MARTIN","RADIADORES SAN MARTIN",16);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (17,"ABERTURAS EL MASTIL","ABERTURAS EL MASTIL",17);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (18,"ARCO MAQUINARIAS S.A","ARCO MAQUINARIAS S.A",18);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (19,"DEBORA S.R.L",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (20,"INDARTUBO S.A","INDARTUBO S.A",20);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (21,"SANITARIOS SAN MARTIN ","SANITARIOS SAN MARTIN ",21);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (22,"AGENCIA OFICIAL FLORESTA NORTE DE JOSE A. ARGIZ Y ","AGENCIA OFICIAL FLORESTA NORTE DE JOSE A. ARGIZ Y ",22);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (23,"CLARIANT ARGENTINA S.A",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (24,"EASY CENCOSUD S,A",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (25,"EUROQUIMICA PRODUCTOS INDUSTRIALES S.A",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (26,"TELEFONIA MOVILES ARGENTINA S.A","TELEFONIA MOVILES ARGENTINA S.A",26);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (27,"ONLYCOM S.A","ONLYCOM S.A",27);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (28,"RULTRANS DE FEDERICO MARTIN ARGUIZONI",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (29,"ANILINAS RIEGER S.A","ANILINAS RIEGER S.A",29);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (30,"CALERA SAN JUSTO S.A","CALERA SAN JUSTO S.A",30);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (31,"CASA MARIO S.A","CASA MARIO S.A",31);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (32,"JORGE OMAR FELDMAN",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (33,"ILIVERIR S.R.L","ILIVERIR S.R.L",33);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (34,"MATAFUEGOS Y SEGURIDAD INDUSTRIAL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (35,"JAVIER REYNOSO CALEFACCIÓN-MONTAJES INDUSTRIALES","JAVIER REYNOSO CALEFACCIÓN-MONTAJES INDUSTRIALES",35);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (36,"SEIPAC SA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (37,"ELECTRO CASAC S.A",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (38,"MOURI CARGAS EMPRESA DE TRANSPORTE","MOURI CARGAS EMPRESA DE TRANSPORTE",38);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (39,"ENVASES DEL PARQUE S.A","ENVASES DEL PARQUE S.A",39);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (40,"CTORRES S.R.L","CTORRES S.R.L",40);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (41,"CARRETERO DE CARRETERO CARLOS ALBERTO","CARRETERO DE CARRETERO CARLOS ALBERTO",41);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (43,"VILMAX S.A","VILMAX S.A",43);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (44,"COMPAÑIA ARGENTINA DE SELLOS Y BOMBAS S.R.L","COMPAÑIA ARGENTINA DE SELLOS Y BOMBAS S.R.L",44);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (45,"MATERIALES SAN FERNANDO S.A","MATERIALES SAN FERNANDO S.A",45);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (46,"SURFACTAN S.A",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (47,"INDAQUIM INDUSTRIALIZACIÓN QUIMICA S.A","INDAQUIM INDUSTRIALIZACIÓN QUIMICA S.A",47);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (48,"ALONSO Y CIA GAS LICUADO ENVASADO S.C.A","ALONSO Y CIA GAS LICUADO ENVASADO S.C.A",48);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (50,"QUIMICA COLOR SRL","QUIMICA COLOR SRL",50);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (51,"B.T.I. SRL","B.T.I. SRL",51);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (52,"ARANIL SA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (53,"AISLANTES SAN JUSTO",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (54,"ALCONIC S.R.L.","ALCONIC S.R.L.",54);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (55,"ALETAN S.R.L.","ALETAN S.R.L.",55);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (56,"ALFA TRANSMISIONES INDUSTRIALES","ALFA TRANSMISIONES INDUSTRIALES",56);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (57,"ALFAMAQ VENTURI S.A.","ALFAMAQ VENTURI S.A.",57);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (58,"ALFAQUIM S.R.L.","ALFAQUIM S.R.L.",58);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (59,"ARSUL S.R.L.","ARSUL S.R.L.",59);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (60,"AURIAL S.R.L.",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (61,"ELINSUR S.R.L","ELINSUR S.R.L",61);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (62,"BBC LUBRICANTES",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (63,"BOBINAJES INDUSTRIALES",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (64,"CLOROSUR I.C.S.A.","CLOROSUR I.C.S.A.",64);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (65,"COMATEC S.R.L.","COMATEC S.R.L.",65);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (66,"DEDAPOL S.R.L",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (67,"DROQUIMAR S.R.L.","DROQUIMAR S.R.L.",67);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (68,"EMBAL CENTER S.A.","EMBAL CENTER S.A.",68);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (69,"FERRETERIA INDUSTRIAL SABUL","FERRETERIA INDUSTRIAL SABUL ",69);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (70,"GAS SAN MARTIN","GAS SAN MARTIN",70);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (71,"GALIGRAFICA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (72,"KELMAR S.A.C.I.F.",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (73,"GRAMMA SEGURIDAD",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (74,"METALURGICA TAMBARA S.R.L.","METALURGICA TAMBARA S.R.L.",74);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (75,"MULTIGARMENT S.R.L.","MULTIGARMENT S.R.L.",75);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (76,"PROANALISIS S.A.","PROANALISIS S.A.",76);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (77,"QBE ASEGURADORA DE RIESGOS DE TRABAJO S.A.","QBE ASEGURADORA DE RIESGOS DE TRABAJO S.A.",77);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (78,"QUIMICA BERGER S.A.","QUIMICA BERGER S.A.",78);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (79,"QUIMACO S.R.L.",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (80,"ROSSI FLET S.R.L.","ROSSI FLET S.R.L.",80);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (81,"SANITARIOS TORINO S.A.",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (82,"SEAL PACK SA","SEAL PACK SA",82);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (83,"TERMITEX S.A.","TERMITEX S.A.",83);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (84,"TECNO-SAN MARTIN S.R.L.","TECNO-SAN MARTIN S.R.L.",84);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (85,"ZINGUERIA SANTA FE","ZINGUERIA SANTA FE",85);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (86,"ZINGUERIA VACALARI",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (87,"RULEMANES MONTANARI E HIJO",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (88,"SALINERA LANUS S.A.","SALINERA LANUS S.A.",88);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (89,"SASPER S.A.","SASPER S.A.",89);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (90,"TUBOS TISA DE ROGELIO EDGARDO CERNADAS","TUBOS TISA DE ROGELIO EDGARDO CERNADAS",90);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (91,"RUNNER DE LIC. ANA ESTELA RONVAUX",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (92,"OXIGENO MAGALI","OXIGENO MAGALI",92);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (93,"MANUCHAR FERNANDO PETROSELLI INTERNO 123","MANUCHAR FERNANDO PETROSELLI INTERNO 123",93);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (94,"MAPEKO VANESA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (95,"MATEXPLA S.A.","MATEXPLA S.A.",95);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (96,"MATIAS REY","MATIAS REY",96);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (97,"MATUBE SILVIA","MATUBE SILVIA",97);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (98,"METALURGICA THEUMA S.R.L.","METALURGICA THEUMA S.R.L.",98);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (99,"AURELEO GUNDIN","AURELEO GUNDIN",99);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (100,"AUTO PARTS","AUTO PARTS",100);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (101,"CALDERAS KALCOR ","CALDERAS KALCOR ",101);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (102,"CALDERAS ","CALDERAS ",102);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (103,"FENOBLOCK","FENOBLOCK",103);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (104,"FERCOMEX ","FERCOMEX ",104);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (105,"GAS NATURAL BAN SA ",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (106,"GARRAFAS","GARRAFAS",106);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (107,"GRUAS LA MATANZA","GRUAS LA MATANZA",107);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (108,"GRUAS MARCELO","GRUAS MARCELO",108);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (109,"HOFFERLE ADOLFO","HOFFERLE ADOLFO",109);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (110,"FARHN S.R.L.",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (111,"FANCY HOUSE","FANCY HOUSE",111);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (112,"PLASTICOS DEL PLATA","PLASTICOS DEL PLATA",112);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (113,"TODO RELLENO","TODO RELLENO",113);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (114,"FERRETERIA HUEMUL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (115,"DEMCOSUR S.R.L.","DEMCOSUR S.R.L.",115);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (116,"SPEEDY","SPEEDY",116);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (117,"GALAY MINERALES","GALAY MINERALES",117);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (118,"AUTOCORD S.A.","AUTOCORD S.A.",118);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (119,"CASA BEATO S.A.","CASA BEATO S.A.",119);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (120,"COMPUTERS DEPOT",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (121,"CLAUDIA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (122,"PATON SUCESION",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (123,"PATON",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (124,"GUSTAVO",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (125,"COMENSE",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (126,"HORCRISA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (128,"TEXTIL LAPRIDA","TEXTIL LAPRIDA",130);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (129,"ING. JOSE MARIA LEIVA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (130,"TUBOSUR S.A.","TUBOSUR S.A.",177);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (131,"NEUMATICOS CASTELAR",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (132,"JULIO MARTINEZ","JULIO MARTINEZ",183);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (133,"KOZINARTE",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (134,"PARQUE COLONIAL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (135,"H2O  TRATAMIENTOS INDUSTRIALES",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (136,"RINO",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (137,"MACGAR",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (138,"EZEQUIEL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (139,"HAEDO SERVICE SRL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (140,"SERPES BALANZAS ELECTRONICAS",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (141,"LUIS PATON ",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (142,"ITALPERFIL","ITALPERFIL",224);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (143,"CONSULTORA INDUSTRIAL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (144,"GAMMA COLOR QUIMICA SRL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (145,"ACQUA MAX  SRL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (146,"SURPOLIMEROS SA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (147,"ROMO MATERIALES DE LA CONSTUCCION SRL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (148,"PACKS","PACKS ",228);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (149,"SANTA ROSA S.A.","SANTA ROSA S.A.",129);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (150,"HUGO DUCO",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (151,"ECO MADERAS","ECO MADERAS",305);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (152,"GALVASUD S.R.L.","GALVASUD S.R.L.",309);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (153,"MIRVAL ",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (154,"OLTEX","OLTEX",186);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (155,"CEPILLOS INDUSTRIALES ARBISER","CEPILLOS INDUSTRIALES ARBISER",304);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (156,"BELTING  ARGENTINA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (157,"TEJEDURIA DE ALBERTO VILLARINO","TEJEDURIA DE ALBERTO VILLARINO",346);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (158,"TODO VAPOR",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (159,"ATECSA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (160,"ELECTROBOM","ELECTROBOM",146);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (161,"MINICARGADORA RETROPERCUTORA BOBCAT ",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (162,"TRANSPORTES RUBEN",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (163,"TENDENCIA URBANA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (164,"PATO MADERAS",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (165,"FAMACOM (TECNICO PANASONIC)",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (166,"BOBINAJES INDUSTRIALES BOZZONE","BOBINAJES INDUSTRIALES BOZZONE",63);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (167,"CAPIALBI",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (168,"CEDINI",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (169,"CONSTRUCCIONES DE MISITI HECTOR","CONSTRUCCIONES DE MISITI HECTOR ",438);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (170,"CLIF TECNOLOGIA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (171,"ZAMORANO",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (172,"CONSTRUTECH",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (173,"ELLIOT",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (174,"ARGENTINA AUTOELEVADORES S.A.","ARGENTINA AUTOELEVADORES S.A.",123);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (175,"SERGIO SOLIZ ",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (176,"ROBERTO MARASCA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (177,"NEUMATICOS CASTELAR ",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (178,"CIFARELLI CHACABUCO",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (179,"CIFARELLI LEVEL",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (180,"TEC SOFT ",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (181,"TUBOSUD S.A.","TUBOSUD S.A. ",481);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (182,"PABLO LOSADA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (183,"GUSTAVO FERNANDEZ - TECHISTA",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (184,"DARIO ANTUNEZ -ALBAÑIL ",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (185,"DIEGO BECERRA -YESERO",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (186,"MARIANA GIUSTI",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (187,"GASISTA-SIMON",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (188,"AGUSTIN-COLOCADOR CERAMICOS",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (189,"TITO SOLDADOR",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (190,"L & L INGENIERIA - PROYECTOS -",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (191,"OBRAS Y SERVICIOS",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (192,"DIEGO GODOY",NULL,NULL);
INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES (193,"SAN JUSTO PUERTAS Y VENTANAS DE ACOSTA",NULL,NULL);


-- PASOS PARA GENERAR LOS INSERTS
-- EJECUTAR EN LA B:
-- SELECT P_ID, A_RAZON_SOCIAL FROM T_PROVEEDORES;
-- TAOMAR EL RESULTADO Y GRABARLO EN UN .CSV, BORRAR LOS DATOS DEL HEADER Y
-- REEMPLAZAR (DESDE EL ECLIPSE) SEG�N:
-- BUSCAR ^(.*)$
-- REEMPLAZAR POR INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL) VALUES ($1);
-- CREAR LA TABLA EN LA A Y EJECUTAR LOS INSERTS DEL PUNTO ANTERIOR.
-- LUEGO EJECUTAR EL SIGUIENTE UPDATE (EN LA A) PARA SETEAR EL P_ID_A y A_RAZONSOCIAL_A 
-- UPDATE T_PROVEEDORES_EQUIV PREQUIV INNER JOIN T_PROVEEDORES PR ON PREQUIV.A_RAZONSOCIAL = PR.A_RAZON_SOCIAL set PREQUIV.A_RAZONSOCIAL_A=PR.A_RAZON_SOCIAL,PREQUIV.P_ID_A=PR.P_ID;
-- RESOLVER LOS P_ID_A == NULLS CON SALEM Y SETEARLOS A MANO
-- HACER UN EXPORT EN CSV Y LUEGO TRANSFORMAR A INSERTS CON LA SIGUIENTE SUSTICION
--  ^(.*)$ POR INSERT INTO T_PROVEEDORES_EQUIV (P_ID, A_RAZONSOCIAL, A_RAZONSOCIAL_A, P_ID_A) VALUES ($1);
