-- T_CORRECCION_FACTURA.A_NRO_CORRECCION POR T_FACTURA.A_NRO_FACTURA
-- T_CORRECCION_FACTURA.A_MONTO POR T_FACTURA.A_MONTO_TOTAL
ALTER TABLE T_FACTURA ADD P_ID_CORRECCION_OLD INT (11);
 
ALTER TABLE `gtl`.`t_factura` MODIFY COLUMN `A_ID_ESTADO_FACTURA` INT(11) DEFAULT NULL;
ALTER TABLE `gtl`.`t_factura` MODIFY COLUMN `F_COND_VENTA_P_ID` INT(11) DEFAULT NULL;
ALTER TABLE `gtl`.`t_factura` MODIFY COLUMN `A_MONTO_FALTANTE` INT(11) DEFAULT NULL;

update T_FACTURA set tipo='FC' where TIPO IS NULL;

INSERT INTO T_FACTURA (A_MONTO_TOTAL, A_NRO_FACTURA, A_ID_ESTADO_FACTURA,A_PRCT_IVA_INSCR,A_PRCT_IVA_NO_INSCR,A_FECHA_EMISION,A_MONTO_FALTANTE,A_ID_TIPO_FACTURA,A_MONTO_IMPUESTOS,A_MONTO_SUBTOTAL,F_REMITO_SALIDA_P_ID,F_COND_VENTA_P_ID,F_NOTA_CREDITO_P_ID,A_ESTADO_IMPRESION,A_USR_CONFIRMACION,F_CLIENTE_P_ID,P_ID_CORRECCION_OLD,TIPO,A_DESCRIPCION,A_ID_ESTADO_CORRECCION,A_VERIFICADA,A_USUARIO_VERIFICADOR,A_ANULADA,A_MONTO_SOBRANTE,A_ES_RECHAZA_CHEQUE,A_GASTOS,A_ID_EST_ANT_CHEQUE, F_CHEQUE_P_ID)
SELECT
A_MONTO,A_NRO_CORRECCION, NULL, A_PRCT_IVA_INSCR, NULL, A_FECHA_EMISION, A_MONTO_FALTANTE, A_ID_TIPO_FACTURA, NULL, A_MONTO_SUBTOTAL, NULL, NULL, NULL, A_ESTADO_IMPRESION, NULL,F_CLIENTE_P_ID, P_ID,TIPO,A_DESCRIPCION,A_ID_ESTADO_CORRECCION,A_VERIFICADA,A_USUARIO_VERIFICADOR,A_ANULADA,A_MONTO_SOBRANTE,A_ES_RECHAZA_CHEQUE,A_GASTOS,A_ID_EST_ANT_CHEQUE, F_CHEQUE_P_ID
FROM T_CORRECCION_FACTURA;

ALTER TABLE t_factura DROP FOREIGN KEY FK1CBAE66DE0760589;	-- F_NOTA_CREDITO_P_ID
ALTER TABLE t_forma_pago DROP FOREIGN KEY FKF8070E66E0760589; -- F_NOTA_CREDITO_P_ID
ALTER TABLE t_movimiento DROP FOREIGN KEY FK85344160B43CC669; -- F_NOTA_DEBITO_P_ID
ALTER TABLE t_movimiento DROP FOREIGN KEY FK85344160E0760589; -- F_NOTA_CREDITO_P_ID
ALTER TABLE t_pago_recibo DROP FOREIGN KEY FKAC8FCE1B43CC669; -- F_NOTA_DEBITO_P_ID

update t_factura f inner join t_factura cc on cc.P_ID_CORRECCION_OLD = f.F_NOTA_CREDITO_P_ID set f.F_NOTA_CREDITO_P_ID = cc.p_id; 
update t_forma_pago fp inner join t_factura cc on cc.P_ID_CORRECCION_OLD = fp.F_NOTA_CREDITO_P_ID set fp.F_NOTA_CREDITO_P_ID = cc.p_id;
update t_movimiento mov inner join t_factura cc on cc.P_ID_CORRECCION_OLD = mov.F_NOTA_DEBITO_P_ID set mov.F_NOTA_DEBITO_P_ID = cc.p_id;
update t_movimiento mov inner join t_factura cc on cc.P_ID_CORRECCION_OLD = mov.F_NOTA_CREDITO_P_ID set mov.F_NOTA_CREDITO_P_ID = cc.p_id;
update t_pago_recibo pr inner join t_factura cc on cc.P_ID_CORRECCION_OLD = pr.F_NOTA_DEBITO_P_ID set pr.F_NOTA_DEBITO_P_ID = cc.p_id;

ALTER TABLE T_FACTURA ADD CONSTRAINT FK1CBAE66DE0760589 FOREIGN KEY (F_NOTA_CREDITO_P_ID) REFERENCES T_FACTURA (P_ID);
ALTER TABLE t_forma_pago ADD CONSTRAINT FKF8070E66E0760589 FOREIGN KEY (F_NOTA_CREDITO_P_ID) REFERENCES T_FACTURA (P_ID);
ALTER TABLE t_movimiento ADD CONSTRAINT FK85344160B43CC669 FOREIGN KEY (F_NOTA_DEBITO_P_ID) REFERENCES T_FACTURA (P_ID);
ALTER TABLE t_movimiento ADD CONSTRAINT FK85344160E0760589 FOREIGN KEY (F_NOTA_CREDITO_P_ID) REFERENCES T_FACTURA (P_ID);
ALTER TABLE t_pago_recibo ADD CONSTRAINT FKAC8FCE1B43CC669 FOREIGN KEY (F_NOTA_DEBITO_P_ID) REFERENCES T_FACTURA (P_ID);










