-- AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

UPDATE T_PRODUCTO_ARTICULO PA
INNER JOIN T_PRODUCTO PROD ON PROD.P_ID = PA.F_PRODUCTO_P_ID
SET PA.F_DIBUJO_P_ID = PROD.F_DIBUJO_P_ID,PA.F_VARIANTE_P_ID = PROD.F_VARIANTE_P_ID,PA.F_COLOR_P_ID = PROD.F_COLOR_P_ID,PA.F_GAMA_P_ID = PROD.F_GAMA_P_ID;

ALTER TABLE T_PRODUCTO DROP COLUMN F_DIBUJO_P_ID;
ALTER TABLE T_PRODUCTO DROP COLUMN F_GAMA_P_ID;
ALTER TABLE T_PRODUCTO DROP FOREIGN KEY FK205010EB85200BC0;
ALTER TABLE T_PRODUCTO DROP COLUMN F_COLOR_P_ID;
ALTER TABLE T_PRODUCTO DROP COLUMN F_VARIANTE_P_ID;

UPDATE T_PRODUCTO_ARTICULO PA
INNER JOIN (
    SELECT PR.P_ID AS PID, X.MINPID AS MINPID
    FROM T_PRODUCTO PR
      INNER JOIN (
        SELECT MIN(P_ID) AS MINPID, TIPO AS TIPO
        FROM T_PRODUCTO
        GROUP BY TIPO
    ) X ON X.TIPO = PR.TIPO
) Z ON Z.PID = PA.F_PRODUCTO_P_ID
SET PA.F_PRODUCTO_P_ID = Z.MINPID;

DELETE FROM T_PRODUCTO WHERE P_ID NOT IN (SELECT F_PRODUCTO_P_ID FROM T_PRODUCTO_ARTICULO);

UPDATE T_PRODUCTO SET A_DESCR='TEÑIDO' WHERE TIPO='TENIDO';
UPDATE T_PRODUCTO SET A_DESCR='ESTAMPADO' WHERE TIPO='ESTAMPADO';

-- BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

drop table t_producto;

CREATE TABLE `t_producto` (
  `TIPO` varchar(31) NOT NULL,
  `P_ID` int(11) NOT NULL,
  `A_DESCR` varchar(255) NOT NULL,
  PRIMARY KEY  (`P_ID`)
) ENGINE=FEDERATED DEFAULT CHARSET=utf8 CONNECTION='mysql://root:s4l3m@192.168.1.250:3306/gtl/t_producto';

drop table t_producto_articulo;

CREATE TABLE `t_producto_articulo` (
  `P_ID` int(11) NOT NULL auto_increment,
  `F_PRODUCTO_P_ID` int(11) NOT NULL,
  `F_ARTICULO_P_ID` int(11) default NULL,
  `F_GAMA_P_ID` int(11) default NULL,
  `F_DIBUJO_P_ID` int(11) default NULL,
  `F_VARIANTE_P_ID` int(11) default NULL,
  `F_COLOR_P_ID` int(11) default NULL,
  PRIMARY KEY  (`P_ID`)
) ENGINE=FEDERATED DEFAULT CHARSET=utf8 CONNECTION='mysql://root:s4l3m@192.168.1.250:3306/gtl/t_producto_articulo';


