drop table T_GRUPO_TIPO_ARTICULO_BASE;
drop table T_GRUPO_TIPO_ARTICULO_GAMA;
drop table T_PRECIO_TIPO_ARTICULO;

create table T_GRUPO_TIPO_ARTICULO_BASE;
create table T_GRUPO_TIPO_ARTICULO_GAMA;
create table T_PRECIO_TIPO_ARTICULO;