INSERT INTO T_ITEM_FACTURA (A_DESCRIPCION, A_IMPORTE, A_CANITDAD, A_UNIDAD, A_PRECIO_UNITARIO, F_FACTURA_P_ID, TIPO)
SELECT F.A_DESCRIPCION, F.A_MONTO_TOTAL, 1, 2, F.A_MONTO_TOTAL, F.P_ID, 'ITFC'
FROM T_FACTURA F
WHERE F.TIPO IN ('ND', 'NC');
