ALTER TABLE T_FACTURA_PROVEEDOR MODIFY A_MONTO_TOTAL DECIMAL(19,3);
ALTER TABLE T_FACTURA_PROVEEDOR MODIFY A_MONTO_SUBTOTAL DECIMAL(19,3);
ALTER TABLE T_FACTURA_PROVEEDOR MODIFY A_MONTO_FALTANTE_POR_PAGAR DECIMAL(19,3);
ALTER TABLE T_FACTURA_PROVEEDOR MODIFY A_IMP_VARIOS DECIMAL(19,3);
ALTER TABLE T_FACTURA_PROVEEDOR MODIFY A_PERCEP_IVA DECIMAL(19,3);
ALTER TABLE T_FACTURA_PROVEEDOR MODIFY A_DESCUENTO DECIMAL(19,3);

ALTER TABLE T_ITEM_FACTURA_PROV MODIFY A_IMPORTE DECIMAL(19,3);
ALTER TABLE T_ITEM_FACTURA_PROV MODIFY A_PRECIO_UNITARIO DECIMAL(19,3);
ALTER TABLE T_ITEM_FACTURA_PROV MODIFY A_PORC_DESC DECIMAL(19,3);
ALTER TABLE T_ITEM_FACTURA_PROV MODIFY a_factor_conv_moneda DECIMAL(19,3);

ALTER TABLE T_MOVIMIENTO MODIFY a_monto DECIMAL(19,3);

