ALTER TABLE t_formula_estampado_cliente MODIFY COLUMN A_NOMBRE VARCHAR(255) DEFAULT NULL;
ALTER TABLE t_formula_aprestado_cliente MODIFY COLUMN A_NOMBRE VARCHAR(255) DEFAULT NULL;
ALTER TABLE t_formula_tenido_cliente MODIFY COLUMN A_NOMBRE VARCHAR(255) DEFAULT NULL;