-- EN LA A

UPDATE T_PARAM_GENERALES SET A_CTA_MAIL_USER = 'administracion@textillevel.com';
UPDATE T_PARAM_GENERALES SET A_CTA_MAIL_PASS = 'smartin4215';

-- EN LA B

UPDATE T_PARAM_GENERALES SET A_CTA_MAIL_USER = 'presupuestos.adm@gmail.com';
UPDATE T_PARAM_GENERALES SET A_CTA_MAIL_PASS = 'mura4855';

