INSERT INTO t_producto VALUES ('ESTAM_CRUDO', 1205, 'ESTAMPADO SOBRE CRUDO');
INSERT INTO t_producto VALUES ('LAVA_TERMOF', 1206, 'LAVADO Y TERMOFIJADO');
INSERT INTO t_producto VALUES ('LAVA__ESP_TERMOF', 1207, 'LAVADO Y TERMOFIJADO (SACANDO CASCARILLAS)');
INSERT INTO t_producto VALUES ('VTA_TELA_CRUD', 1208, 'VENTA TELA CRUDA');
