insert into T_PROVINCIA values (1,'Buenos Aires'),
 (2,'Catamarca'),
 (3,'Chaco'),
 (4,'Chubut'),
 (5,'Córdoba'),
 (6,'Corrientes'),
 (7,'Entre Ríos'),
 (8,'Jujuy'),
 (9,'La Pampa'),
 (10,'La Rioja'),
 (11,'Mendoza'),
 (12,'Misiones'),
 (13,'Neuquén'),
 (14,'Río Negro'),
 (15,'Salta'),
 (16,'San Juan'),
 (17,'Formosa'),
 (18,'San Luis'),
 (19,'Santa Fe'),
 (20,'Santiago del Estero'),
 (21,'Tierra del Fuego'),
 (22,'Tucumán'),
 (23,'Santa Cruz'),
 (24,'Capital Federal');