-- EJECUTAR LA B:
CREATE TABLE `T_ARTICULO_EQUIV` (
  `P_ID` INT(10) NULL,
  `A_NOMBRE` VARCHAR(100) NULL,
  `A_DESCR` VARCHAR(255) NULL,
  `A_DESCR_A` VARCHAR(255) NULL,
  `A_NOMBRE_A` VARCHAR(100) NULL,
  `P_ID_A` INT(10)
);

-- EJECUTAR INSERTS EN LA B (VER COMO GENERARLOS ABAJO EN "PASOS PARA GENERAR LOS INSERTS"):

INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (1,"AP 2.40","ALGODON POLYESTER ANCHO 2,40","ALGODON POLYESTER ANCHO 2,40","AP 2.40",1);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (3,"TAP 1,50","TAPICERIA ANCHO 1,50","TAPICERIA ANCHO 1,50","TAP 1,50",3);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (4,"TAP 3.00","TAPICERIA ANCHO 3.00","TAPICERIA ANCHO 3.00","TAP 3.00",4);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (5,"AP 1,95","ALGODON POLYESTER ANCHO 1,95","ALGODON POLYESTER ANCHO 1,95","AP 1,95",5);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (6,"AP 1,50","ALGODON POLYESTER 1,50","ALGODON POLYESTER 1,50","AP 1,50",6);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (7,"AA 2,40","ALGODON 100% ANCHO 2,40","ALGODON 100% ANCHO 2,40","AA 2,40",7);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (8,"POL 1,50","POLYESTER 100% ANCHO 1,50","POLYESTER 100% ANCHO 1,50","POL 1,50",8);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (9,"POL 3.00","POLYESTER 100% ANCHO 3,00",NULL,NULL,16);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (10,"TAP 2.80","TAPICERIA 2.80 MTRS",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (11,"AP 2.10","ALGODON POLYESTER ANCHO 2.10 MTRS","ALGODON POLYESTER ANCHO 2.10 MTRS","AP 2.10 ",26);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (12,"AP 1.60","ALGODON POLYESTER ANCHO 1.60 MTRS","ALGODON POLYESTER 1.60","AP 1.60",19);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (13,"PCL 2.80","PERCAL , ANCHO 2.80 MTRS",NULL,NULL,12);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (14,"TAP 2.10","TAPICERIA  ANCHO 2.10","TAPICERIA ANCHO 2.10 MTRS","TAP 2.10",22);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (15,"PCL 2.50","PERCAL  ANCHO 2.50","PERCAL ANCHO 2.50","PCL 2.50",38);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (16,"AA 2.50","ALGODON 100%","ALGODON 100%","AA 2.50 ",30);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (17,"AA 1.60","100% ALGODON ANCHO 1.60 MTRS","ALGODON 100% 1.6 MTS","AA 1.60",15);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (18,"POL 1.80","POLYESTER 100 % 1.80 ANCHO",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (19,"PCL 2.70 ","PERCAL ANCHO 2.70","PERCAL 2.70 MTS","PCL 2.70",11);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (20,"AP 1.05","ALGODON POLYESTER ANCHO 1.05 METROS",NULL,NULL,33);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (21,"GUARD 1.60","TELA PARA GUARDAPOLVO ANCHO 1.60","TELA PARA GUARDAPOLVO ANCHO 1.60","GUARD 1.60",23);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (22,"VENTA DE TELA","VENTA DE TELA","PERCAL 2.60 MTRS","VENTA DE TELA",21);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (23,"GAB .1.65","GABARDINA ANCHO 1.65",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (24,"AP 2.05","ALGODON POLYESTER 2.05",NULL,NULL,29);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (25,"AP 1.80","ALGODON POLYESTER","ALGODON POLIESTER","AP 1.80",47);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (26,"AA 3.00","ALGODON 100%","ALGODON 100 %","AA 3.00",46);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (27,"DEVOLUCION SIN PROCESAR","DEVOLUCION SIN PROCESAR",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (28,"GAB 1.60","GABARDINA 1.60 ANCHO","GABARDINA 1.60 ANCHO","GAB 1.60",62);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (29,"PCL 2.25","PERCAL AP 2.25",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (30,"PCL 1.65","PERCAL 1.65 ANCHO",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (31,"PCL 3.00","AP PERCAL 3.00 ANCHO","PERCAL ANCHO 3.00","PCL 3.00",37);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (32,"AP 1.60","ALG- POL 1.60 ANCHO","ALGODON POLYESTER 1.60","AP 1.60",19);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (33,"POL 1.60","POLIESTER 1.60 ANCHO","POLYESTER 1.60 MT","POL 1.60",17);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (34,"POL 3.20","POLYESTER 3.20 M ANCHO",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (35,"AP 2.00","AP 2.00 ANCHO ","ALGODON POLYESTER 2.00 METROS","AP 2.00",31);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (36,"AP 3.00","AP 3.00 ANCHO",NULL,NULL,35);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (37,"AP 3.40","3.40ANCHO",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (38,"AP 2.25","ALG/POL 2.25 ANCHO",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (39,"AP 2.50","AP 2.50","AOLGODON POLYESTER 2.50 ANCHO","AP 2.50 ",27);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (40,"AP 2,60","AP 2,60",NULL,NULL,32);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (41,"AP 1,55","AP 1,55",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (42,"AP 2.70","AP2.70","ALGOHODON POLYESTER ","AP 2.70",39);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (43,"PONGEE 2.10","PONGEE 2.10","PONGEE 2.10 ANCHO","PONGEE 2.10",61);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (44,"PONGEE 1.40","PONGEE 1.40",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (45,"PONGEE 3.00","PONGEE 3.00",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (46,"PONGEE 2.80","PONGEE 2.80",NULL,NULL,NULL);
INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES (47,"AP 2,95","AP 2,95",NULL,NULL,NULL);

-- PASOS PARA GENERAR LOS INSERTS
-- EJECUTAR EN LA B:
-- SELECT P_ID, A_NOMBRE, A_DESC FROM T_ARTICULO;
-- TAOMAR EL RESULTADO Y GRABARLO EN UN .CSV, BORRAR LOS DATOS DEL HEADER Y
-- REEMPLAZAR (DESDE EL ECLIPSE) SEGÚN:
-- BUSCAR ^(.*)$
-- REEMPLAZAR POR INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR) VALUES ($1);
-- CREAR LA TABLA EN LA A Y EJECUTAR LOS INSERTS DEL PUNTO ANTERIOR.
-- LUEGO EJECUTAR EL SIGUIENTE UPDATE (EN LA A) PARA SETEAR EL P_ID_A
-- UPDATE T_ARTICULO_EQUIV EQ INNER JOIN T_ARTICULO ART ON ART.A_NOMBRE = EQ.A_NOMBRE SET EQ.A_DESCR_A = ART.A_DESC, EQ.P_ID_A = ART.P_ID, EQ.A_NOMBRE_A=ART.A_NOMBRE;
-- RESOLVER LOS P_ID_A == NULLS CON SALEM Y SETEARLOS A MANO
-- HACER UN EXPORT EN CSV Y LUEGO TRANSFORMAR A INSERTS CON LA SIGUIENTE SUSTICION
--  ^(.*)$ POR INSERT INTO T_ARTICULO_EQUIV (P_ID, A_NOMBRE, A_DESCR, A_DESCR_A, A_NOMBRE_A, P_ID_A) VALUES ($1);
