-- EJECUTAR LA B:
CREATE TABLE `T_CLIENTE_EQUIV` (
  `P_ID` INT(10) NULL,
  `A_NRO` INT(10) NULL,
  `A_RAZON_SOCIAL` VARCHAR(255) NOT NULL,
  `P_ID_A` INT(10)
);


-- EJECUTAR INSERTS EN LA B (VER COMO GENERARLOS ABAJO EN "PASOS PARA GENERAR LOS INSERTS"):

INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (1,1,"TEXTIL LEVEL S.A.",1);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (2,29,"ASEKAMEX S.A",2);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (3,95,"ADOLFO MICHIA",3);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (4,51,"HORACIO BOTTINI",4);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (5,59,"RODOLFO RENE BIANCHI",5);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (6,37,"BALTEX DE OSVALDO L., ADRIAN N,OMAR I. BALDINI S.H",6);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (7,56,"BONETTI HNOS.",7);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (8,6,"BANCHERO ARMANDO CESAR",8);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (9,23,"BELLAMORE CLAUDIO",9);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (10,13,"BONETTI JUAN A.",10);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (11,83,"GUSTAVO A. CARRASCO",11);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (12,25,"CASA ROMA S.A",12);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (13,36,"COOPERATIVA DE TRABAJO VINIPLAST LIMITADA",13);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (14,52,"CUERTOPS SOC. RESP. LIMITADA",14);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (15,8,"CHAMI JOSE CLAUDIO",15);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (16,60,"CHILETEX",16);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (17,90,"DE LUCA JUAN CARLOS",17);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (18,611,"DALESSANDRO MOLINA DIEGO DAVID",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (19,22,"DAKUBA SACIFIYA",19);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (20,18,"ALBERTO B. DARLAN",20);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (21,3,"DEANTONI LEONARDO DAVID",21);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (22,39,"DIETEX S.A",22);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (23,40,"DINAY S.R.L",23);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (24,42,"DENIMTEX S.R.L",24);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (26,99,"FRANCO E HIJOS S.R.L",26);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (27,113,"DIEGO A. FELDMANN",27);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (28,50,"FELEJA S.A",28);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (29,73,"FERREYRO JORGE R.",29);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (30,46,"FIRVER S.R.L",30);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (31,64,"FLORMAR  DE MORINI CARLOS ERNESTO",31);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (32,71,"GRUPO RG S.R.L DATOS DE DURY EN OBSERVACIONES",32);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (33,80,"GUILLERMO CARLOS PARRA",33);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (34,79,"GIACHINO ALFREDO, GIACHINO LUIS, GIACHINO PEDRO",34);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (35,47,"HUCATEX S.R.L",35);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (36,24,"IGLESIAS HECTOR ANTONIO",36);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (37,78,"JC S.R.L",37);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (38,93,"KALEJMAN ELENA RUTH",38);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (39,16,"LAPZENZON MARCELO ARIEL TIENE CUENTA 166",39);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (40,91,"MAYFRATEX S.A",40);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (41,74,"MACATEX S.A",41);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (42,4,"MELLA PEREZ LUIS ERASMO Y PIRO JULIO OSCAR S.H",42);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (43,109,"MANUFACTURA TEXPORT S.A",43);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (44,19,"MUÑOZ HECTOR HORACIO",44);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (45,30,"MAVI TEXTIL",45);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (46,49,"MARIQUEL S.R.L.",46);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (47,65,"NEBO TEXTIL S.H DE PRUSKI W. Y PRUSKI D.",47);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (48,72,"NICOTEX DE ALBERTO S. NICOSIA",48);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (49,89,"PEDERNIK DAVID",49);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (50,27,"PARANATEX S.R.L",50);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (51,41,"PERCLES S.A",51);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (52,38,"RONEU S.A",52);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (53,112,"RODRIGUEZ DANIEL HORACIO",53);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (54,84,"SOLTEX S.A.I.C.A.",54);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (55,86,"SCALTER S.R.L",55);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (56,14,"RUBEN SEGURA PROCESOS",56);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (57,15,"SABARIS NORBERTO ENRIQUE",57);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (58,5,"SARCO MARIA CRISTINA",58);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (59,17,"SOAE ADOLFO",59);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (60,110,"MIGUEL SOKOLOWSKI S.A",60);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (61,57,"SUMINISTROS HECAR S.A.C.I,A",61);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (62,85,"TEXTIL SOLUNA S.R.L",62);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (63,75,"TEJEDURIA STAMATI S.A",63);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (64,67,"TEX MAVI S.R.L",64);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (65,35,"TEXTIL DE TOMASO DE HECTOR Y CARLOS DE TOMASO S.H",65);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (66,92,"TEXTIL FIBREX S.A.I.C.F E I",66);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (67,111,"PABLO TARLON",67);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (68,54,"TEXTILES UNIDOS S.A",68);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (69,28,"TEJEDURIA GUEMES S.R.L",69);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (70,11,"TEJIDOS DE ARTE SORPRESA (...)",70);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (71,34,"TEJIDOS DEL MIRADOR S.A",71);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (72,31,"TEJIDOS DEL RINCON S.A",72);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (73,9,"TEXTILERA AMERICANA",73);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (74,43,"TEXTIL URUAR",74);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (75,20,"TILVAN S.A",75);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (76,66,"TEXTIL BOCHA DE RODRIGUEZ N. Y FEDERICO S.H",76);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (77,96,"TEXTIL DOSS S.R.L",77);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (78,97,"VIVONA MARIA LAURA",78);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (79,69,"VEKSTEIN PEDRO A.",79);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (80,48,"VILLARINO ALBERTO",80);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (81,76,"YABAR FABIO GABRIEL",81);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (82,81,"HONEKER JOSE Y HONEKER ROQUE",82);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (84,88,"TEXTIL FARATEX SRL",84);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (85,105,"INTERDISEÑO",85);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (86,130,"EXTRA BALL SRL",86);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (87,101,"TEXSATEX S.A.",87);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (88,122,"TEJEDURIA SAENZ PEÑA SA",88);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (89,137,"MAR CAL SA",89);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (90,104,"TELAS PARA DECORACION",90);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (92,53,"SUCESION DE SILVIO H. ERRAMUSPE",92);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (93,205,"PEPE",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (94,12,"JOSE SALEM",94);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (95,68,"CARLOS BANCHERO",95);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (96,70,"LOLA PRADA",96);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (97,94,"GUILLERMO POLERO",97);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (98,63,"INNOVARTE",98);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (99,108,"TEXTIL SH      MASSUD",100);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (100,61,"D'ALESSANDRO DIEGO",18);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (101,599,"RODOLFO BIANCHI 2º",163);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (102,77,"LUIS BIANCHI",142);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (103,500,"EZEQUIEL OURFALI",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (104,114,"PUCHE JORGE",101);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (105,87,"GOYTEX SRL",106);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (106,106,"NESTOR GHIGLIONE",110);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (107,102,"BARBARO SOCIEDAD COLECTIVA",109);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (108,127,"ZUY",120);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (109,119,"CORTINERIA CONFORT S.R.L.",112);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (110,166,"MARCELO LAPZENZON AP 240",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (111,121,"BITOCHI MIGUEL ANGEL",114);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (112,120,"RAUL PRUSKI",115);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (113,116,"CARINA PEDROZZA",113);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (114,115,"STABIC SAN LUIS SA",104);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (115,125,"MARCHESI",117);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (116,103,"FIORELLA",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (117,126,"DANIEL MAJUL",121);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (118,2,"SADASA",102);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (119,82,"PEPE",93);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (120,98,"DALSEMTEX SRL",99);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (121,100,"TEXTIL LATINO",108);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (123,231,"MARCAL SA",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (124,117,"VH FABRIC SRL",107);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (125,118,"SUMI TOT",111);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (126,123,"FAESA TEXTIL",105);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (127,124,"COMPAÑIA TEXTIL",116);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (128,128,"EDUL ALBERTO",119);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (129,711,"KRIKORIAN JOSE ESTEBAN",118);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (130,510,"ROALTEX",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (131,129,"PALACIO JAVIER",123);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (132,132,"EKITAKO SA",124);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (133,1414,"RUBEN SEGURA METROS",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (134,134,"CLADD INDUSTRIA TEXTIL ARGENTINA S.A.",127);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (135,131,"LIOL RUBEN ANTONIO",125);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (136,133,"TEJEDURIA LAS MARIAS",126);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (137,135,"GURNIAK",128);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (138,136,"LOMBARDO VERONICA Y LOMBARDO SEBASTIAN HNOS",129);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (139,138,"SR NATALIO",130);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (140,139,"SAUL LITARDO",131);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (141,141,"LOMBARDO MIGUEL",134);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (142,142,"IMPAC 2",136);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (143,143,"OGANDO PABLO",135);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (144,145,"GUSMERINI FERNANDO JAVIER",140);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (145,144,"PUERTO TEXTIL",138);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (146,146,"DAVID SERRANO",139);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (147,147,"MONTAGNE OUTDOORS S.A.",141);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (148,722,"NICOTEX CUENTA METROS",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (149,148,"NORTEXTIL",143);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (150,213,"INDUSTRIA TEXTIL TESO TEX S.R.L.",144);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (151,7272,"NICOTEX NUEVA",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (152,149,"COMPAÑIA TEXTIL RODA S.A.",146);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (153,941,"CLIENTE DE GUILLERMO POLERO",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (154,151,"DOG TAG SRL",148);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (155,140,"ACORAZADO S.A.",133);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (156,155,"LAGUITEX DE TILVAN S.A.",149);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (157,152,"JOTA DE DE JAIME DREYZIN",150);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (158,154,"BMC CUENTA CANJE X C/M AP2.4 PAGA C/ 2 M AP1.5",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (159,533,"SUCESION DE SILVIO. H. ERRAMUSPE",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (160,153,"JORGE ALASSIA",156);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (161,162,"SCOZZARI HNOS",158);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (162,165,"SANCHEZ MILTON GASTON",154);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (163,169,"BENJAMIN SALOMON SAFDIE",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (164,167,"GURUYON S.R.L.",161);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (165,170,"CARLOS STORK",164);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (166,175,"TOBATEL S.A.",168);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (167,177,"EDUARDO CAÑENSKY",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (168,176,"EZEQUIEL NOTTA",173);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (169,182,"SOS LINDA",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (170,186,"NESTOR GONZALEZ PATO",NULL);
INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES (171,188,"TECENDO DE GUILLERMO VASQUEZ",176);


-- PASOS PARA GENERAR LOS INSERTS
-- EJECUTAR EN LA B:
-- SELECT P_ID, A_NRO_CLIENTE, A_RAZON_SOCIAL FROM T_CLIENTE;
-- TAOMAR EL RESULTADO Y GRABARLO EN UN .CSV, BORRAR LOS DATOS DEL HEADER Y
-- REEMPLAZAR (DESDE EL ECLIPSE) SEG�N:
-- BUSCAR ^(.*)$
-- REEMPLAZAR POR INSERT INTO T_CLIENTE_EQUIV (P_ID, A_RAZON_SOCIAL, A_NRO) VALUES ($1);
-- CREAR LA TABLA EN LA A Y EJECUTAR LOS INSERTS DEL PUNTO ANTERIOR.
-- LUEGO EJECUTAR EL SIGUIENTE UPDATE (EN LA A) PARA SETEAR EL P_ID_A
-- UPDATE T_CLIENTE_EQUIV CL INNER JOIN T_CLIENTE CA ON CA.A_NROCLIENTE = CL.A_NR set CL.P_ID_A = CA.P_ID;
-- RESOLVER LOS P_ID_A == NULLS CON SALEM Y SETEARLOS A MANO
-- HACER UN EXPORT EN CSV Y LUEGO TRANSFORMAR A INSERTS CON LA SIGUIENTE SUSTICION
--  ^(.*)$ POR INSERT INTO T_CLIENTE_EQUIV (P_ID, A_NRO, A_RAZON_SOCIAL, P_ID_A) VALUES ($1)


