-- TRIVIAL, SIN COMENTARIOS

CREATE TABLE `T_COND_VENTA_EQUIV` (
  `P_ID` INT(10) NULL,
  `P_ID_A` INT(10) NOT NULL
);

INSERT INTO T_COND_VENTA_EQUIV (P_ID, P_ID_A) VALUES (5,5);
INSERT INTO T_COND_VENTA_EQUIV (P_ID, P_ID_A) VALUES (6,6);
INSERT INTO T_COND_VENTA_EQUIV (P_ID, P_ID_A) VALUES (7,7);
INSERT INTO T_COND_VENTA_EQUIV (P_ID, P_ID_A) VALUES (8,9);
