-- EJECUTAR LA B:
CREATE TABLE `T_PRECIO_MATERIA_PRIMA_EQUIV` (
  `P_ID` INT(10) NULL,
  `A_ALIAS` VARCHAR(50) NULL,
  `A_SIGLAS` VARCHAR(50) NULL,
  `A_DESCR_MP` VARCHAR(255) NULL,
  `A_PROV` VARCHAR(255) NULL,
  `P_ID_A` INT(10)
);


-- EJECUTAR INSERTS EN LA B (VER COMO GENERARLOS ABAJO EN "PASOS PARA GENERAR LOS INSERTS"):

INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (7,"AUXI","NCA","AUXIBLE NCA ","SANYOCOLOR S.A.",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (8,"AUXI","C 14","AUXITRANSP C 14","SANYOCOLOR S.A.",841);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (9,"AUXI","C14 163001","AUXITRANSP C 14 163001","SANYOCOLOR S.A.",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (10,"COSC","PLD","CROSCOLOR PLD ","SANYOCOLOR S.A.",1405);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (11,"COSC","OZ","CROSCOLOR OZ ","SANYOCOLOR S.A.",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (32,"VIOLETA","2B","VIOLETA KAYARUS 2B 100%","SANYOCOLOR S.A.",458);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (33,"ROJO","3BL","ROJOKAYARUS 3BL 200%","SANYOCOLOR S.A.",592);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (34,"VOLETA","RL","VIOLETA LUMACRON RL 200%","SANYOCOLOR S.A.",225);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (35,"PARDO","SER ","PARDO AMARILLO LUMACRON SER 150%","SANYOCOLOR S.A.",2227);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (36,"ROSA","FR","ROSA KAYARUS FR 200% ","SANYOCOLOR S.A.",2130);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (37,"AZUL","BRL","AZUL KAYARUS BRL 200%","SANYOCOLOR S.A.",1322);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (38,"AZUL","FBLE","AZULLUMACRON FBLE 150%","SANYOCOLOR S.A.",581);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (39,"AZUL","BC","AZUL SANYOTHRENE BC","SANYOCOLOR S.A.",226);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (40,"VERDE","XB","VERDE  SANYOTHRENE XB","SANYOCOLOR S.A.",594);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (41,"NARANJA","2GL","NARANJA KAYARUS 2 GL 200%","SANYOCOLOR S.A.",589);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (42,"AMARILLO","PG 200%","AMARILLO KAYARUS PG 200%","SANYOCOLOR S.A.",2394);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (66,"AMARILLO","SANYOTHRENE","AMARILLO SANYOTHRNE GC ","SANYOCOLOR S.A.",657);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (67,"PARDO","SANYOTHRENE","PARDO SANYOTHRENE","SANYOCOLOR S.A.",591);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (68,"VERDE OLIVA","SANYOTHRENE","VERDE OLIVA SANYOTHRENE","SANYOCOLOR S.A.",380);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (69,"ROJO ","FBB","ROJO SANYOTHRENE FBB","SANYOCOLOR S.A.",381);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (70,"RUBINA","LUMACRON 2GFL","RUBINA LUMACRON 2GFL","SANYOCOLOR S.A.",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (71,"AMARRILLO","SANYOTHRENE","AMARILLO SANYOTHRENE GC","SANYOCOLOR S.A.",378);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (72,"AZUL","SANYOTHRENE","AZUL SANYOTHRENE RS","SANYOCOLOR S.A.",581);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (73,"AUXIBEL ","SG 100","AUXIBEL SG 100","SANYOCOLOR S.A.",360);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (74,"NEGRO","KAYARUS CH","NEGRO KAYARUS CH 1400%","SANYOCOLOR S.A.",446);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (75,"TURQUESA","SGL","TURQUESA LUMACRON SGL 200%","SANYOCOLOR S.A.",447);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (76,"NEGRO ","LUMACRON ","NEGRO LUMACRON EXNSF 300%","SANYOCOLOR S.A.",205);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (77,"NARANJA","H3R","NARANJA LUMACRON H3R 200%","SANYOCOLOR S.A.",2627);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (78,"ESCARLATA","GS 200%","ESCARLATA LUMACRON GS 200%","SANYOCOLOR S.A.",2174);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (79,"ROJO","LUMACRON FB","ROJO LUMACRON FB 200%","SANYOCOLOR S.A.",840);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (80,"VIOLETA ","KAYARUS 2B","VIOLETA KAYARUS 2B 100%","SANYOCOLOR S.A.",458);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (120,"ALCALI","RH","ALCALI RH 2301","SANYOCOLOR S.A.",1086);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (121,"AC","045","AC 045","SANYOCOLOR S.A.",1087);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (122,"ROJO","KAYARUS","ROJO KAYARUS BWS 200 % ","SANYOCOLOR S.A.",592);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (123,"AMARILLO ","LUMACRON","AMARILLO LUMACRON E3G 200%","SANYOCOLOR S.A.",2173);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (124,"ESCARLATA","KAYARUS","ESCARLATA KAYARUS F2G 200%","SANYOCOLOR S.A.",2128);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (125,"TURQUESA","FBL","TURQUESA KAYARUS FBL 400%","SANYOCOLOR S.A.",2145);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (151,"VIRCOGUARD","FCD","VIRCOGUARD","SANYOCOLOR S.A.",3640);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (152,"VIRCOSCOUR","JX","VIRCOSCOUR JX 101","SANYOCOLOR S.A.",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (19,"AURITEX","FIX","AURITEX FIX","PRODUCTOS QUIMICOS AURIAL S.R.L",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (20,"CARRIER ","PE","CARRIER PE","PRODUCTOS QUIMICOS AURIAL S.R.L",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (21,"AURITEX ","QUEL KE","AURITEX QUEL KE","PRODUCTOS QUIMICOS AURIAL S.R.L",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (145,"CONTENEDOR","IBC","CONTENEDOR","DALGAR S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (46,"EMULTEX","EMUL","EMULTEX C/ANTICORRIMIENTO ","VORTEX ARGENTINA S.A",1733);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (60,"FLOPRINT ","FLO","FLOPRINT 150W (CON AMONIACO) TAMBOR X 130","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (84,"CARRIER","TEX","CARRIER TEX E BALDE X25","VORTEX ARGENTINA S.A",305);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (85,"LIMPIADOR ","CILINDROS","LIMPIADOR DE CILINDROS TEX","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (86,"PARDO","RM/40","PARDO RM/40 TEX BALDE POR 20","VORTEX ARGENTINA S.A",518);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (88,"BLANCO","A 80","BLANCO DIRECTO A-80","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (92,"AMARILLO","R TEX","AMARILLO R TEX BALDE X 20","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (93,"NEGRO","R TEX","NEGRO R TEX BALDE POR 20","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (110,"BLANCO","RKB","BLANCO RKB2 TEX ","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (127,"ANTICORRIMIENTO","TEX","ANTICORRIMIENTO TEX","VORTEX ARGENTINA S.A",519);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (146,"BLANCO","RKB","BLANCO RKB2/50 TEX","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (147,"MARINO R","87/13","AZUL MARINO R 87/13","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (148,"VERDE","TEX","VERDE B TEX ","VORTEX ARGENTINA S.A",1796);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (149,"NEGRO","R TEX","NEGRO R TEX ","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (150,"FLOPRINT","AMONIACO","FLOPRINT","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (156,"ANTIESPUMANTE","H10","ANTIESPUMANTE","VORTEX ARGENTINA S.A",1430);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (157,"ROJO","F4RV","ROJO F4RV TEX","VORTEX ARGENTINA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (166,".",".","CORRESPINDE A FC DE CTA1","SODIMAC FALABELLA S.A",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (65,"UCP","205","UCP 205","RULTRANS DE FEDERICO MARTIN ARGUIZONI",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (126,"RULEMAN","6308","6308 SA SLAF","RULTRANS DE FEDERICO MARTIN ARGUIZONI",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (138,"LEFT","206","LEFT 206","RULTRANS DE FEDERICO MARTIN ARGUIZONI",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (139,"RIO","RULS","RIO RULS","RULTRANS DE FEDERICO MARTIN ARGUIZONI",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (144,"UC ","206","UC 206","RULTRANS DE FEDERICO MARTIN ARGUIZONI",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (153,"RULEMANES","6006","RULEMANES 6006 ZZ","RULTRANS DE FEDERICO MARTIN ARGUIZONI",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (160,"MS","ATN","69005 MS NTN","RULTRANS DE FEDERICO MARTIN ARGUIZONI",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (94,"ALFAMILASA","R","ALFAMILASA","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (95,"NEGRO","VSF","NEGRO SOLIDO EVERDIRECT VSF","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (98,"AMARILLO","3GL","AMARILLO SERILENE  GL","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (111,"AMARILLO","SERILENE","AMARILLO SERILENE 3GL 200%","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (112,"PARDO","SERILENE","PARDO AMARILLO SERILENE RLS 150 %","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (113,"ANARANJADO","EVERDIRECT","ANARANJADO SUPRE EVERDIRECT 2GL CONC","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (132,"TEXOFIN","GWS","TEXOFIN GWS","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (133,"ESCARLATA","F2G","ESCARLATA  LUZ EVERIDECT F2G","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (134,"OPTIBLANC","3NL","OPTIBLANC 3NL CONC","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (136,"ANARANJADO","DIRECT","ANARANJADO SUPRA EVERDIRECT 2GL CONC","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (154,"SERILENE","XXT","NEGRO SERILENE","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (155,"AZUL","RL","AZUL SERILENE RL 150%","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (159,"RUBI","BL","RUBI SUPRA EVERIDECT BL","SEIPAC SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (43,"CHASIS","CHAS","UN CHASIS PARA TRANSPORTAR UN CONTENEDOR","MOURI CARGAS EMPRESA DE TRANSPORTE",388);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (53,"CHASIS","VIAJE","UN CHASIS PARA TRANSPORTAR CONTENEDOR","MOURI CARGAS EMPRESA DE TRANSPORTE",388);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (54,"DEMORA","VIAJE","DEMORA DE  UN DIA ","MOURI CARGAS EMPRESA DE TRANSPORTE",427);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (12,"LIG","RTE S","LIGANTE BAIPRINT RTE S","B.T.I. SRL",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (96,"BAICRIL","S","BAICRYL 700 S","B.T.I. SRL",729);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (99,"LASER","BTO","LASER BTO S","B.T.I. SRL",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (17,"ARAFIX","GHS","ARAFIX GHS","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (18,"NEGRO","PES KXNF","NEGRO PES ","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (22,"SYNOLUZ","2GL","NARANJA SYNOLUZ 2GL","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (23,"PES","LFB","ROJO PES LFB","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (24,"ARACET","R","VIOLETA ARACET R","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (25,"PES","KGL","TURQUESA PES KGL","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (29,"SYNOWHITE","B3B","SYNOWHITE B3B","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (30,"SYNOWHITE","EBF","SYNOWHITE EBF ","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (31,"ARAPON","W","ARAPON W","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (55,"ROJO","F3B","ROJO SYNOLUZ F3B","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (56,"ROJO","BWS","ROJO SYNOLUZ BWS","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (57,"RUBI","H-2GL","RUBI PES H-2GL","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (61,"VIOLETA","SYNOLUZ","VIOLETA SYNOLUZ 4 B 50","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (62,"AZUL","SINOLUZ","AZUL SINOLUZ BRL 50","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (63,"ROSA","SINOLUZ","ROSA SINOLUZ  FR 50","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (158,"HF","BBN","ROJO ARAFEIX HF BBN","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (167,"1","1","RUBI SYNOLUZ BL","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (168,"1","1","PARDO AMARILLO PES H2RL","ARANIL SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (14,"ORADET","ORA"," ORADET 201","ALETAN S.R.L.",2117);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (162,".",".","ORADET ","ALETAN S.R.L.",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (141,"BOBINA","STRICH","BOBINA DE POLIETILENO STRICH","DEDAPOL S.R.L",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (142,"BOBINA","CRISTAL","BOB CRISTAL 20X 50 BUL 4","DEDAPOL S.R.L",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (143,"BOBINA ","CRISTAL","BOBINA CRISTAL 45 X40 BUL 6","DEDAPOL S.R.L",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (87,"CINTA","SIN LOGO","CTA. SIN LOGO","EMBAL CENTER S.A.",534);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (89,"A 174","A 174","TERMILASA","QUIMICA BERGER S.A.",672);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (83,"GRUAS","9 M","SERVICIO DE GRUAS ","GRUAS LA MATANZA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (97,"A","","1","CLAUDIA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (44,"CL240","CL","GRABADO DE CILINDROS","COMENSE",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (45,"1","1","AJUSTE","COMENSE",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (15,"TUBOS ","TUB","TUBOS DE CARTON ","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (16,"TUBOS","TUBS","TUBOS DE CARTON ","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (26,"TUBOS","CARTON","TUBOS DE CARTON 1550MMX2MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (27,"TUBOS","CARTON","TUBOS DE CARTON 1600MMX 2MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (47,"TUBOS","CARTON","TUBOS CARTON 1650MMX2MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (48,"TUBOS","CARTON","TUBOS DE CARTON 2000MMX 2MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (49,"TUBOS","CARTON","TUBOS DE CARTON 2500MM X2MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (64,"TUBOS","CARTON","TUBOS DE CARTON 2100MMX2MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (103,"TUBOS ","CARTON","TUBOS DE CARTON 1450MMX2MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (104,"TUBOS","CARTON","TUBOS CARTON 1350MMX2X50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (105,"TUBOS","CARTON","TUBOS DE CARTON 1250MMX2MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (115,"TUBOS","CARTON","TUBOS DE CARTON 1400 MMX3MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (116,"TUBOS ","CARTON","TUBOS DE CARTON 1500MMX 3MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (117,"TUBOS","CARTON","TUBOS DE CARTON 1600MMX3MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (118,"TUBOS ","CARTON","TUBOS DE CARTON 1640MMX3MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (119,"TUBOS","CARTON","TUBOS DE CARTON 2010MMX3MMX50MM","TEXTIL LAPRIDA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (1,".",".","SERVICIO DE PLANOS.","ING. JOSE MARIA LEIVA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (4,"ABONO","","ABONO CORRESPONDIENTE A DIC2010Y ENERO 2011","ING. JOSE MARIA LEIVA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (5,"AN.AGUA","","ANALISIS DE AGUA COMPLETO","ING. JOSE MARIA LEIVA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (6,"JABA","","GASTOS POR MEDICION DE JABALINAS","ING. JOSE MARIA LEIVA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (2,"RA","","RUEDA AUTOELEVADOR","NEUMATICOS CASTELAR",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (3,"CT","","CAMBIO DE TUBOS","JULIO MARTINEZ",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (13,"CALDERA","TAC","TAC 101 CALDERA","H2O  TRATAMIENTOS INDUSTRIALES",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (28,"REPARA","MARTILLO","REPARACION DE MARTILLO HIDRONEUMATICO","HAEDO SERVICE SRL",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (50,"SERVICE","SER","SEVICE DE BALANZA","SERPES BALANZAS ELECTRONICAS",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (51,"ESTUDIOS","EST ","3 MONI. EN AMB. DE TRAB.CON ENTREGA DE INFORMES","CONSULTORA INDUSTRIAL",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (52,"BALNCO ","CONC","BLANCO CONC.","GAMMA COLOR QUIMICA SRL",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (58,"MM","440P","MM 440-P (CALDERA)","ACQUA MAX  SRL",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (59,"MM 440","M 440","MM 440 P (CALDERA)","ACQUA MAX  SRL",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (82,"MMHH","CALDERA","MMHH0P(CALDERA)","ACQUA MAX  SRL",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (90,"MM","CALDERA","MM 440P(CALDERA)","ACQUA MAX  SRL",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (81,"V3A","POLIMEROS","POLIMEROS","SURPOLIMEROS SA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (91,"BOLSAS","NEGRAS","BOBINAS DE 53X60 NEGRO EN TUBOS","PACKS",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (100,"TEXOFIN","GWS","TEXOFIN GWS","SANTA ROSA S.A.",816);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (101,"ALFAMILASA","R","ALFAMILASA R","SANTA ROSA S.A.",1456);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (102,"SERILENE","XXT","NEGRO SERILENE","SANTA ROSA S.A.",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (114,"TEXOWET","FFDN","TEXOWET FFDN","SANTA ROSA S.A.",842);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (106,"MADERAS","MAD","MADERAS","ECO MADERAS",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (107,"FLETE","FL","FLETE","ECO MADERAS",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (108,"TEFLON ","CON GRAFITO","VALVULA ESFERICA A INOX 316 TEFLON REFORZADO CON G","MIRVAL ",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (109,"3 CUERPOS 2","INOX","VALVULA ESFERICA ACTUADOR NEUMATICO","MIRVAL ",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (131,"CLINGER","METALICA","PLANCHA CLINGER 4408 3Â´Â´CON MALLA METALICA 1500X","MIRVAL ",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (128,"POMOS","NEGROS","POMOS NEGROS","OLTEX",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (129,"POMOS ","AMARILLO","POMOS AMARILLOS","OLTEX",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (130,"PICOS","ESFEROGRAFICOS","PICOS ESFEROGRAFICOS","OLTEX",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (135,"POMO","OLTEX","POMOS OLTEX COLOR NEGRO","OLTEX",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (161,"1","1","POMOS NEGROS","OLTEX",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (137,"GLASS","MESH","GLASS/PTFE MESH BROWN 4X4 MM BPEA","BELTING  ARGENTINA",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (140,"TELA","A/P","TELA A/P ANCHO 2.40","TEJEDURIA DE ALBERTO VILLARINO",1265);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (163,"1","1","BOBINADO DE MOTOR 5 CAB","BOBINAJES INDUSTRIALES BOZZONE",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (164,"1","1","LIGANTE BAIPRINT RTE- S ","CEDINI",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (165,"1","1","ANTIESPUMANTE SRE","CEDINI",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (169,"TUBOS","TBS","TUBOS","TUBOSUD S.A.",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (170,"1","1","TUBOS DE CARTON DE 1250 X 50","TUBOSUD S.A.",NULL);
INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES (171,"1","1","TUBOS DE CARTON DE 1500 X 50","TUBOSUD S.A.",2930);

-- PASOS PARA GENERAR LOS INSERTS
-- EJECUTAR EN LA B:
/*
SELECT PMT.P_ID, PMT.A_ALIAS, PMT.A_SIGLAS,MP.A_DESCRIPCION, PP.A_RAZON_SOCIAL
FROM T_PRECIO_MATERIA_PRIMA PMT
INNER JOIN T_MATERIA_PRIMA  MP ON MP.P_ID = PMT.F_MATERIA_PRIMA_P_ID
INNER JOIN T_LISTA_PRECIOS_PROV LP ON LP.P_ID=PMT.F_LISTA_DE_PRECIOS_P_ID
INNER JOIN T_PROVEEDORES PP ON PP.P_ID = LP.F_PROVEEDOR_P_ID;
*/

-- TOMAR EL RESULTADO Y GRABARLO EN UN .CSV, BORRAR LOS DATOS DEL HEADER Y
-- REEMPLAZAR (DESDE EL ECLIPSE) SEGÚN:
-- BUSCAR ^(.*)$
-- REEMPLAZAR POR INSERT INTO T_PRECIO_MATERIA_PRIMA_EQUIV (P_ID, A_ALIAS, A_SIGLAS, A_DESCR_MP, A_PROV, P_ID_A) VALUES ($1);
-- CREAR LA TABLA EN LA A Y EJECUTAR LOS INSERTS DEL PUNTO ANTERIOR.
-- RESOLVER LOS P_ID_A == NULLS CON SALEM Y SETEARLOS A MANO

-- querys útiles:
/*
SELECT PMT.P_ID, PMT.A_ALIAS, PMT.A_SIGLAS,MP.A_DESCRIPCION, PP.A_RAZON_SOCIAL
FROM T_PRECIO_MATERIA_PRIMA PMT
INNER JOIN T_MATERIA_PRIMA  MP ON MP.P_ID = PMT.F_MATERIA_PRIMA_P_ID
INNER JOIN T_LISTA_PRECIOS_PROV LP ON LP.P_ID=PMT.F_LISTA_DE_PRECIOS_P_ID
INNER JOIN T_PROVEEDORES PP ON PP.P_ID = LP.F_PROVEEDOR_P_ID
ORDER BY PP.A_RAZON_SOCIAL, MP.A_DESCRIPCION;


select equiv.p_id, equiv.a_alias,X.ppal,equiv.a_siglas,X.ppsig, equiv.A_DESCR_MP, X.ppmp
from T_PRECIO_MATERIA_PRIMA_EQUIV equiv
inner join (
  SELECT PMT.P_ID as ppid, PMT.A_ALIAS as ppal, PMT.A_SIGLAS as ppsig,MP.A_DESCRIPCION as ppmp, PP.A_RAZON_SOCIAL as ppprov
  FROM T_PRECIO_MATERIA_PRIMA PMT
  INNER JOIN T_MATERIA_PRIMA  MP ON MP.P_ID = PMT.F_MATERIA_PRIMA_P_ID
  INNER JOIN T_LISTA_PRECIOS_PROV LP ON LP.P_ID=PMT.F_LISTA_DE_PRECIOS_P_ID
  INNER JOIN T_PROVEEDORES PP ON PP.P_ID = LP.F_PROVEEDOR_P_ID
-- ) X on equiv.A_PROV = X.ppprov and equiv.a_siglas= X.ppsig;
-- ) X on equiv.A_PROV = X.ppprov and equiv.a_alias= X.ppal;
) X on equiv.A_PROV = X.ppprov and equiv.A_DESCR_MP=X.ppmp
order by equiv.p_id;
*/
